spring.application.name=RestonetBackend
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/PDBRESTO
spring.datasource.username=RESTO
spring.datasource.password=p12
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#spring.datasource.url=jdbc:firebirdsql://127.0.0.1:3050/C:/RECO5/DonneesR/RECO.fdb?encoding=UTF8
#spring.datasource.username=gilsa
#spring.datasource.password=4048pv134
#spring.jpa.database-platform=org.hibernate.dialect.FirebirdDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
# SSL Configuration
server.ssl.enabled=true
server.ssl.key-store-type=JKS
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=123456

#mailservice
# Gmail SMTP Configuration (Free)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anaaross1999@gmail.com
spring.mail.password=xrha xbwa fzlx vstn
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Enable debug
spring.mail.properties.mail.debug=true